# This workflow will build and run a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: easyFlight-airline-service

on:
  push:
    branches: [ "pre-hosting" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Start new process in the background
        run: go run cmd/api/main.go &