# This workflow will build and run a Golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: easyFlight-airline-service

on:
  push:
    branches: [ "pre-hosting" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...



      - name: Find and stop existing process
        run: |
          PID=$(pgrep -f "go run main.go")
          if [ -n "$PID" ]; then
            echo "Stopping existing process with PID $PID"
            kill $PID
            sleep 2 # Wait for the process to stop
          else
            echo "No existing process found"
          fi

      - name: Start new process in the background
        run: go run main.go &